language: objective-c
osx_image: xcode10.1
matrix:
    include:
        - name: "MockoloTests"
          script: swift test -Xswiftc -DDEBUG
        - name: "MockoloBinary"
          script: swift build -c release -Xswiftc -static-stdlib
