name: Build Actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.xcode.os }}
    strategy:
      matrix:
        xcode:
          - { os: macos-11, version: "12.5.1" }
          - { os: macos-11, version: "13.0" }
          - { os: macos-12, version: "13.3.1" }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode ${{ matrix.xcode.os }}
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode.version }}.app
          xcodebuild -version
          swift --version
          swift package --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v -c release
