name: Build Actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
    steps:
      - uses: sidepelican/setup-swift@swift58
        with:
          swift-version: "5.8"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show versions
        run: |
          xcodebuild -version
          swift --version
          swift package --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v -c release
