name: Release

on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: macos-12
    steps:
    - uses: sidepelican/setup-swift@swift58
      with:
        swift-version: "5.8"
    - uses: actions/checkout@v3
    - name: Create the binary
      run: ./install-script.sh -s . -t mockolo -d . -o mockolo.tar.gz
    - name: Upload the binary
      uses: actions/upload-artifact@v3
      with:
        name: mockolo
        path: mockolo.tar.gz

  check-portability:
    needs: build-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, ubuntu-22.04, ubuntu-20.04]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: mockolo
    - name: Unpack the binary
      run: tar -xvf mockolo.tar.gz
    - name: Run the binary
      run: ./mockolo --version

  deploy-binary:
    needs: check-portability
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: mockolo
    - name: Deploy the binary
      uses: softprops/action-gh-release@v1
      with:
        files: mockolo.tar.gz
